# Generated by Django 2.2.3 on 2019-07-09 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ownername', models.CharField(max_length=20, null=True, verbose_name='ownername')),
                ('book_name', models.CharField(max_length=20, null=True, verbose_name='bookname')),
                ('original_price', models.IntegerField(null=True, verbose_name='originalprice')),
                ('selling_price', models.IntegerField(null=True, verbose_name='sellingprice')),
                ('address', models.CharField(max_length=150, null=True, verbose_name='address')),
                ('ph_num', models.IntegerField(verbose_name='phonenumber')),
                ('bookpassword', models.CharField(max_length=20, null=True, verbose_name='bookpassword')),
            ],
        ),
    ]
