# Generated by Django 2.2.3 on 2019-07-09 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_owner_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='verified',
            field=models.BooleanField(default=True),
        ),
    ]
