# Generated by Django 2.2.3 on 2019-07-09 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20190709_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
