# Generated by Django 2.2.3 on 2019-07-10 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20190709_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='verified1',
            field=models.BooleanField(default=True),
        ),
    ]
