# Generated by Django 2.2.3 on 2019-07-10 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_owner_verified1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='verified1',
        ),
    ]
