# Generated by Django 2.2.3 on 2019-07-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_remove_owner_verified1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='verified',
            field=models.BooleanField(default=True),
        ),
    ]
