# Generated by Django 2.2.3 on 2019-07-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20190710_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
